name: flutter_ris
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  image_picker: ^1.0.0
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logonn.png
  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: fonts/IBMPlexMono-BoldItalic.ttf
        - asset: fonts/IBMPlexMono-Bold.ttf
        - asset: fonts/IBMPlexMono-ExtraLight.ttf
        - asset: fonts/IBMPlexMono-Italic.ttf
        - asset: fonts/IBMPlexMono-Light.ttf
        - asset: fonts/IBMPlexMono-LightItalic.ttf
        - asset: fonts/IBMPlexMono-Medium.ttf
        - asset: fonts/IBMPlexMono-MediumItalic.ttf
        - asset: fonts/IBMPlexMono-Regular.ttf
        - asset: fonts/IBMPlexMono-SemiBold.ttf
        - asset: fonts/IBMPlexMono-SemiBold.ttf
        - asset: fonts/IBMPlexMono-SemiBoldItalic.ttf
        - asset: fonts/IBMPlexMono-Thin.ttf
        - asset: fonts/IBMPlexMono-ThinItalic.ttf

