// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7SvvaoJJqAyqLtNHrMrJ9uD_tsbgcZH8',
    appId: '1:673951335021:web:36491f94ae44518ca67564',
    messagingSenderId: '673951335021',
    projectId: 'photoland-d1476',
    authDomain: 'photoland-d1476.firebaseapp.com',
    storageBucket: 'photoland-d1476.appspot.com',
    measurementId: 'G-ZTX3HDVJ6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLmAEaf-fDrjMXW6wgHb_-xtg73lm0FQ',
    appId: '1:673951335021:android:b3fe684bbaf71ba1a67564',
    messagingSenderId: '673951335021',
    projectId: 'photoland-d1476',
    storageBucket: 'photoland-d1476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNnDNlkxNiXo5PfDo0VMbKCZYa4-XKYfc',
    appId: '1:673951335021:ios:4cf62f93a3041db2a67564',
    messagingSenderId: '673951335021',
    projectId: 'photoland-d1476',
    storageBucket: 'photoland-d1476.appspot.com',
    iosBundleId: 'com.example.flutterRis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNnDNlkxNiXo5PfDo0VMbKCZYa4-XKYfc',
    appId: '1:673951335021:ios:01b5275bc2f2d6e7a67564',
    messagingSenderId: '673951335021',
    projectId: 'photoland-d1476',
    storageBucket: 'photoland-d1476.appspot.com',
    iosBundleId: 'com.example.flutterRis.RunnerTests',
  );
}
